[book]
authors = ["Trushant-Adeshara-UM"]
language = "en"
multilingual = false
src = "src"
title = "hardware_template"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/MassRobotics-FnF-Challenge/hardware_template/tree/main"
edit-url-template = "https://github.com/MassRobotics-FnF-Challenge/hardware_template/edit/main/{path}"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
